ScopeLift/token-shielder

package.json, yarn.lock
Closes #6 
- Upgraded to next 13, and this pr builds off of #5
=> Upgrade to Next 13

netlify.toml
=> Configure automatic deployments

components/TxForm.tsx, pages/index.tsx, tsconfig.json
Hey all, as I'm preparing to integrate railgun quickstart sdk features into our tx form, I didn't want to pull the import into index.tsx only to refactor later, so I thought I'd break the form out into a component now. Let me know what you think!
=> Break out tx-form into a component

components/TxForm.tsx, hooks/useNotifications.tsx, pages/_app.tsx, utils/networks.ts
- Add toast for transactions and notifications
Closes #23
=> Add notification toast

hooks/useNotifications.tsx
- When looking at #46 I noticed the toast flow wasn't working properly for transactions so I fixed it in this pr
[Screencast from 2023-01-20 10-48-53.webm](https://user-images.githubusercontent.com/12705146/213743480-61fac3d4-bdee-4afd-9aad-5c25f2917382.webm)
=> Fix notification toast flow

components/TxForm.tsx, contexts/TokenContext.tsx, hooks/useNotifications.tsx, hooks/useRailgunTx.tsx, hooks/useTokenAllowances.tsx, hooks/useTokenBalances.tsx, hooks/useTokenList.tsx, pages/index.tsx, utils/constants.ts, utils/networks.ts
Closes #40 
Closes #49 
Closes #36
- shields base token
- adds weth, consumable from useToken hook
- refactors the shield tx stuff into a hook
=> Shield base token

hooks/useNotifications.tsx
- Move toast to bottom left
- Make success toast dismissable
- Add link to success toast
Closes #53 
Closes #54
=> Fix toast issues 

components/TxForm.tsx
- Fix need to approve a native token
=> Fix approve on native token

components/HowTo.tsx, components/TxForm.tsx, pages/_app.tsx, pages/index.tsx, styles/globals.css
Closes https://github.com/ScopeLift/railgun-shielder/issues/22, open to feedback on styles since I'm no designer 😅
=> style: gradients and containers

components/Header.tsx, components/HowTo.tsx, components/TxForm.tsx, pages/_app.tsx, public/tokenlist.json
- Fixes app name in various locations
- Fixes styles that were lost when #75 was merged
=> fix/app name + styles

components/ReviewTransactionModal.tsx, components/TxForm.tsx, hooks/useResolveUnstoppableDomainAddress.tsx, pages/send.tsx
- Resolve unstoppable domain to railgun address
- This pr depends on the form validation changes
Closes #19 
[Screencast from 2023-01-31 22-35-13.webm](https://user-images.githubusercontent.com/12705146/215939091-49a38ca1-f3f1-44a4-b2a1-c5408b9bc5a1.webm)
=> Support unstoppable domains as a recipient

components/TxForm.tsx
- Add button with outline style that adds the link to the clipboard.
- The form pr should probably get in before this one
Closes #20
=> Add copy send link button

components/TxForm.tsx
- Make mobile form responsive
-
=> Fix form on mobile

components/TokenSelectionModal.tsx, hooks/useNotifications.tsx
- Prevent duplicate toasts
Closes #90
=> Prevent duplicate toasts on custom token error

components/TokenSelectionModal.tsx, components/TxForm.tsx
- Add placeholder text
Closes #104
=> Add placeholder text

components/ReviewTransactionModal.tsx, components/TxForm.tsx
- Don't clear address
Closes #111 
[Screencast from 2023-02-20 12-41-14.webm](https://user-images.githubusercontent.com/12705146/220172021-35da51c2-35df-4dfe-8b50-b596e27d98b1.webm)
=> Don't clear address

components/TxForm.tsx
- Create allowance for amount
Closes #112
=> Remove max int allowance

components/TxForm.tsx, hooks/useResolveUnstoppableDomainAddress.tsx, utils/constants.ts, utils/string.ts
- Run validation on change
- Only show `Copy link` when valid address
- Only call unstoppable when address has a valid ending
- Move unstoppable resolution to validation so we don't need to disable submit
- Remove right padding
Closes #102
=> Improvements around unstoppable domain

components/TxForm.tsx
- Added textarea and modified placeholder to be a full address
Closes #110
=> Change to textarea and fit whole address

components/ReviewTransactionModal.tsx, hooks/useRailgunTx.tsx, hooks/useShieldPrivateKey.tsx, styles/globals.css, utils/railgun.ts
=> Confirmation modal explains the `sign` call

components/HowItWorks.tsx
=> "How it works" copy changes

components/Header.tsx
=> Fix position of "Connect Wallet" to top right

components/TokenSelectionModal.tsx
- Reset search term in token modal
Closes #123
=> Set search term to '' onClick

hooks/useNotifications.tsx
- Handle multiple notification updates in rapid succession
Closes #127
=> Remove hook level ref

components/ReviewTransactionModal.tsx, hooks/useRailgunTx.tsx
=> Return shield error in review modal if tx fails before it's sent

components/Footer.tsx, components/PrivacyPolicyModal.tsx
- Add privacy policy as modal in footer
=> Add privacy policy
